### ISSUE TITLE
Dockerfile.prod and it's varieties are not getting detected. 

### ISSUE THREAD

**Issue by AquamanRanda** [d1y/dockerfile.zed#1]
I have attached a screenshot of the issue: 

![CleanShot 2024-02-23 at 11 32 36](https://github.com/d1y/dockerfile.zed/assets/41387473/e7e19edf-c74b-44ee-abfb-f800ad1403af)

**Comment by d1y** [comment]
Yep. now only matches Dockerfile
https://github.com/d1y/dockerfile.zed/blob/5fe1290d7ea20323e3305e28df8cb52d68ad9621/languages/dockerfile/config.toml#L3

**Comment by d1y** [comment]
I'm not sure whether fuzzy matching is possible in zed. vscode-docker's file matching is written like this:
https://github.com/microsoft/vscode-docker/blob/main/package.json#L1518-L1520
<img width="259" alt="image" src="https://github.com/d1y/dockerfile.zed/assets/45585937/bf6f3cb1-339c-4c5c-a139-39d44ab26e69">

**Comment by sinlov** [comment]
> I'm not sure whether fuzzy matching is possible in zed. vscode-docker's file matching is written like this: https://github.com/microsoft/vscode-docker/blob/main/package.json#L1518-L1520 <img alt="image" width="259" src="https://private-user-images.githubusercontent.com/45585937/307241647-bf6f3cb1-339c-4c5c-a139-39d44ab26e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjI1MTgsIm5iZiI6MTcwODgyMjIxOCwicGF0aCI6Ii80NTU4NTkzNy8zMDcyNDE2NDctYmY2ZjNjYjEtMzM5Yy00YzVjLWExMzktMzlkNDRhYjI2ZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDAwNTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MGJkNGQ0ZDVkMTFkNzRiMmUyMWZjNzcyNTk1N2MxZTRkZDc4NTkwMjgyY2UzZjVhNzVkOTUyZjE1YzIzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UYHkbqTjWKG_vq7psAqyGOUM1wBxeiXCAUUEsXoDtiQ">

just config like this

```toml
path_suffixes = ["Dockerfile", "dockerfile", "s6"]
```

<img width="983" alt="image" src="https://github.com/d1y/dockerfile.zed/assets/3433415/5509e637-7454-4264-9f92-3a337849c3c6">

**Comment by jianghoy** [comment]
> > I'm not sure whether fuzzy matching is possible in zed. vscode-docker's file matching is written like this: https://github.com/microsoft/vscode-docker/blob/main/package.json#L1518-L1520 <img alt="image" width="259" src="https://private-user-images.githubusercontent.com/45585937/307241647-bf6f3cb1-339c-4c5c-a139-39d44ab26e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjI1MTgsIm5iZiI6MTcwODgyMjIxOCwicGF0aCI6Ii80NTU4NTkzNy8zMDcyNDE2NDctYmY2ZjNjYjEtMzM5Yy00YzVjLWExMzktMzlkNDRhYjI2ZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDAwNTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MGJkNGQ0ZDVkMTFkNzRiMmUyMWZjNzcyNTk1N2MxZTRkZDc4NTkwMjgyY2UzZjVhNzVkOTUyZjE1YzIzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UYHkbqTjWKG_vq7psAqyGOUM1wBxeiXCAUUEsXoDtiQ">
> 
> just config like this
> 
> ```toml
> path_suffixes = ["Dockerfile", "dockerfile", "s6"]
> ```
> 
> <img alt="image" width="983" src="https://private-user-images.githubusercontent.com/3433415/307559412-5509e637-7454-4264-9f92-3a337849c3c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4ODk1NjYsIm5iZiI6MTcwODg4OTI2NiwicGF0aCI6Ii8zNDMzNDE1LzMwNzU1OTQxMi01NTA5ZTYzNy03NDU0LTQyNjQtOWY5Mi0zYTMzNzg0OWMzYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTkyNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjNlYmQwNWRjNzUyYTQ1YzQyM2RlZTM0YTZiNTdkNTg3ZWIyMmEwMTdkY2FmN2M1ZTY0YTRhMjczZTI4MDgyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z0Gf4n__i-aKDF67fjlYUmCN5d8y8QU53n4DyZpoyxo">

I believe here the problem is people uses 3(!) naming conventions for multiple `Dockerfile` files in the same directory:
```
*.Dockerfile
Dockerfile.*
*.dockerfile
```
And I believe it comes down to whether `zed` support matching by prefix, or better, some sort of regex or not.

**Comment by d1y** [comment]
As far as I know, regular matching is not supported yet

**Comment by d1y** [comment]
I believe this is the same thread: https://github.com/zed-industries/zed/issues/8466

**Comment by rosingrind** [comment]
I did work around this by adding to `~/.config/zed/settings.json`:
```json
{
  "file_types": {
    "Dockerfile": ["Dockerfile", "Dockerfile.local"]
  }
}
```
I think that's pretty and simple. Thanks for the extension!

**Comment by channyein87** [comment]
I tried the below config and doesn't work for me. I have couple of `Dockerfile-xyz` files.

```json
{
  "file_types": {
    "Dockerfile": ["Dockerfile", "Dockerfile-*"]
  }
}
```

**Comment by d1y** [comment]
> I tried the below config and doesn't work for me. I have couple of `Dockerfile-xyz` files.
> 
> ```json
> {
>   "file_types": {
>     "Dockerfile": ["Dockerfile", "Dockerfile-*"]
>   }
> }
> ```

https://github.com/zed-industries/zed/issues/10997#issuecomment-2077839161

**Comment by d1y** [comment]
> I tried the below config and doesn't work for me. I have couple of `Dockerfile-xyz` files.
> 
> ```json
> {
>   "file_types": {
>     "Dockerfile": ["Dockerfile", "Dockerfile-*"]
>   }
> }
> ```

Now it can work, and the main has merged this feature

**Comment by obahareth** [comment]
@d1y Thanks for merging this. Is the only option right now to add this to user settings, or is it possible to let path_suffixes handle this, e.g.

```rust
path_suffixes = ["Dockerfile", "Containerfile", "Dockerfile*"]
```

**Comment by Arcitec** [comment]
I am new here and was researching if I need to add `Containerfile` manually, but I can answer this now for anyone who's curious:

https://github.com/zed-extensions/dockerfile/blob/main/languages/dockerfile/config.toml#L3

It's already a supported filename by default:

```js
path_suffixes = ["Dockerfile", "Containerfile", "dockerfile"]
```

Anyone who wants to add *more* filenames can use the instructions from the readme (you only need to list the additions):

https://github.com/zed-extensions/dockerfile#configuration
