### ISSUE TITLE
Make the same extension for Containerfile.

### ISSUE THREAD

**Issue by DemoDevv** [d1y/dockerfile.zed#3]
it's just a suggestion, but I think that using this extension, it shouldn't be difficult to create an extension for Containerfiles, which are very similar to Dockerfiles, and the coloring on zed would be very useful.it's just a suggestion, but I think that using this extension, it shouldn't be difficult to create an extension for Containerfiles, which are very similar to Dockerfiles, and the coloring on zed would be very useful.

**Comment by d1y** [comment]
After reading the [discussion here](https://github.com/containers/buildah/discussions/3170), I think it’s okay to use dockerfile highlighting

**Comment by Arcitec** [comment]
I am new here and was researching if I need to add `Containerfile` manually, but I can answer this now for anyone who's curious:

https://github.com/zed-extensions/dockerfile/blob/main/languages/dockerfile/config.toml#L3

It's already a supported filename by default:

```js
path_suffixes = ["Dockerfile", "Containerfile", "dockerfile"]
```

Anyone who wants to add *more* filenames can use the instructions from the readme (you only need to list the additions):

https://github.com/zed-extensions/dockerfile#configuration
